server:
    port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: "${MYSQL_PASSWORD:1234}"
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/my-notes-db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: "${MYSQL_USER:root}"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
