server:
    port: 8080

#  matching-strategy is important for spring security path matcher
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "${MYSQL_USER}"
    password: "${MYSQL_PASSWORD}"
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT}/${MYSQL_DB_NAME:my-notes-db}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    liquidbase:
    defer-datasource-initialization:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
token:
  secret: "${TOKEN_SECRET}"
  expiration_time: "${TOKEN_EXPIRATION_TIME:604800000}"